hg_ovh (){
	#local hgpath=/usr/local/bin/hg
	local hgpath=$(which hg)
	if [ $# -lt 1 ]
	then
		$hgpath
	fi

	if [ $# -eq 1 ]
	then
		$hgpath $1 --remotecmd bin/hg
	fi
	
	if [ $# -ge 2 ]
	then
		local action=$1
		shift
		$hgpath $action --remotecmd bin/hg $*
	fi
}

export PATH=$PATH:~/bin
export SVN_SSH='ssh -i /Users/TisseurDeToile/.ssh/id_dsa_vcs'

alias xcode='open -a xcode'
alias text='open -a TextEdit'
alias pre='open -a Preview'
#alias l='ls'
#alias ll='ls -l'
#alias la='ls -a'
alias lo='logout'
alias c='clear'
alias ttop='top -U $USER'
#Aliases
alias lsd='ls --group-directories-first'
alias lsl='ls -l'
alias lsh='ls -lh'
alias ls1='ls -1'
alias lc='wc -l'
alias gh='history | grep'
alias fs='du --max-depth=1 -h'
alias c='clear'
alias pg='ping www.google.fr'
